from django.shortcuts import render
from django.http import JsonResponse
import json
import time
import random
import os
import pandas as pd
import numpy as np
from ml.predictor import HCPPredictor

# Define paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(BASE_DIR, 'data', 'hcp_data.csv')

# Load environment variables from .env file if present
ENV_PATH = os.path.join(BASE_DIR, '.env')
if os.path.exists(ENV_PATH):
    with open(ENV_PATH, 'r') as f:
        for line in f:
            if '=' in line and not line.strip().startswith('#'):
                k, v = line.strip().split('=', 1)
                os.environ[k.strip()] = v.strip().strip('"').strip("'")


# Global cache for data and predictor model
_df_cached = None
_predictor_cached = None

def get_hcp_data_and_predictor():
    """Lazy loads, trains, and caches the HCP dataset and ML predictor using the JAKAFI schema."""
    global _df_cached, _predictor_cached
    if _df_cached is not None and _predictor_cached is not None:
        return _df_cached, _predictor_cached
        
    predictor = HCPPredictor()
    if os.path.exists(CSV_PATH):
        # Train model on current CSV
        predictor.train(CSV_PATH)
        df = pd.read_csv(CSV_PATH)
        
        # Enforce data types
        df['prior_week_rx'] = pd.to_numeric(df['prior_week_rx'], errors='coerce').fillna(0).astype(int)
        df['current_week_rx'] = pd.to_numeric(df['current_week_rx'], errors='coerce').fillna(0).astype(int)
        df['follow_up_status'] = df['follow_up_status'].fillna('None')
        
        # Generate ML predictions
        df['Predicted_Next_Week_Rx'] = predictor.predict_trends(df)
        
        # Calculate priorities
        scores = []
        reasons_list = []
        for _, row in df.iterrows():
            score, reasons = predictor.calculate_priority_score(row)
            scores.append(score)
            reasons_list.append("; ".join(reasons))
            
        df['Priority_Score'] = scores
        df['Priority_Reasons'] = reasons_list
        
        _df_cached = df
        _predictor_cached = predictor
    else:
        _df_cached = pd.DataFrame()
        _predictor_cached = predictor
        
    return _df_cached, _predictor_cached

def chat_page(request):
    """Renders the chatbot interface page with JAKAFI workspace metrics."""
    df, _ = get_hcp_data_and_predictor()
    
    # Calculate JAKAFI metrics for the sidebar status widget
    stats = {
        'total_hcps': len(df) if not df.empty else 0,
        'action_needed': len(df[df['follow_up_status'] == 'None']) if not df.empty else 0,
    }
    return render(request, 'chatbot/index.html', {'stats': stats})

def chat_export(request):
    """Returns the last query result as a downloadable Markdown file."""
    last_query = request.session.get('last_query', 'Report')
    last_response = request.session.get('last_response', '')
    if not last_response:
        from django.http import HttpResponseNotFound
        return HttpResponseNotFound('No previous result to export. Run a query first.')

    filename = f"mosaic_report_{last_query.lower().replace(' ', '_')[:40]}.md"
    content = f"# Mosaic AI Report\n\n**Query:** {last_query}\n\n---\n\n{last_response}\n\n---\n*Generated by Mosaic JAKAFI Assistant*"
    from django.http import HttpResponse
    response = HttpResponse(content, content_type='text/markdown; charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response

def filter_count_api(request):
    """Handles sidebar filter update requests (POST only) to return dynamic counts."""
    if request.method != 'POST':
        return JsonResponse({'error': 'Invalid request method. Only POST is allowed.'}, status=400)
    
    try:
        data = json.loads(request.body)
        filters = data.get('filters', {})
    except json.JSONDecodeError:
        return JsonResponse({'error': 'Invalid JSON format.'}, status=400)
        
    df, _ = get_hcp_data_and_predictor()
    total_count = len(df)
    
    # Apply filters
    filtered_df = apply_sidebar_filters(df, filters)
    filtered_count = len(filtered_df)
    
    return JsonResponse({
        'total': total_count,
        'filtered': filtered_count
    })


def apply_sidebar_filters(df, filters):
    """Filters the HCP dataframe based on active sidebar filter options from client."""
    if not filters:
        return df

    filtered_df = df.copy()

    # Filter by channel
    channels = filters.get('channel', [])
    if channels:
        filtered_df = filtered_df[filtered_df['channel'].isin(channels)]

    # Filter by writer_status
    writer_statuses = filters.get('writer_status', [])
    if writer_statuses:
        filtered_df = filtered_df[filtered_df['writer_status'].isin(writer_statuses)]

    # Filter by patient_type
    patient_types = filters.get('patient_type', [])
    if patient_types:
        filtered_df = filtered_df[filtered_df['patient_type'].isin(patient_types)]

    # Filter by territory
    territories = filters.get('territory', [])
    if territories:
        filtered_df = filtered_df[filtered_df['territory'].isin(territories)]

    # Filter by threshold days for action-needed (follow-up = None) alerts
    threshold = filters.get('threshold', 14)
    if threshold is not None and 'received_date' in filtered_df.columns:
        from datetime import datetime
        as_of_date = datetime(2026, 3, 6)
        
        def check_threshold(row):
            if row.get('follow_up_status') != 'None':
                return True
            try:
                rec_date = datetime.strptime(str(row.get('received_date')), "%m-%d-%Y")
                waiting_days = (as_of_date - rec_date).days
                return waiting_days >= threshold
            except Exception:
                return True
                
        filtered_df = filtered_df[filtered_df.apply(check_threshold, axis=1)]

    return filtered_df

def construct_gemini_prompt(message, df, filters=None):
    """Retrieves context and builds a detailed JAKAFI RAG prompt for the frontend Gemini client."""
    retrieved = retrieve_relevant_rows(message, df, top_k=12)
    retrieved_df = pd.DataFrame(retrieved)
    retrieved_csv_str = retrieved_df.to_csv(index=False) if not retrieved_df.empty else ""
    
    total_hcps = len(df)
    action_needed = len(df[df['follow_up_status'] == 'None'])
    direct_rx = df[df['channel'] == 'Direct']['current_week_rx'].sum()
    spp_rx = df[df['channel'] == 'SPP']['current_week_rx'].sum()
    new_writers = len(df[df['writer_status'] == 'New Writer'])
    new_patients = len(df[df['patient_type'] == 'New Patient'])
    
    summary_stats = f"""
Global Dataset Summary Stats:
- Total JAKAFI HCPs: {total_hcps}
- Alerts requiring follow-up (follow_up_status == 'None'): {action_needed}
- Direct Channel Rx: {direct_rx} prescriptions
- SPP Channel Rx: {spp_rx} prescriptions
- New Writers: {new_writers}
- New Patients alert: {new_patients}
"""

    active_filter_notes = []
    if filters:
        if filters.get('channel'):
            active_filter_notes.append(f"Channel: {', '.join(filters['channel'])}")
        if filters.get('writer_status'):
            active_filter_notes.append(f"Writer Status: {', '.join(filters['writer_status'])}")
        if filters.get('patient_type'):
            active_filter_notes.append(f"Patient Type: {', '.join(filters['patient_type'])}")
        if filters.get('territory'):
            active_filter_notes.append(f"Territory: {', '.join(filters['territory'])}")
        if filters.get('threshold') is not None:
            active_filter_notes.append(f"Follow-up threshold: >={filters['threshold']} days")
            
    filter_context = ""
    if active_filter_notes:
        filter_context = "The user has active sidebar filters applied to the dashboard:\n" + "\n".join([f"- {note}" for note in active_filter_notes]) + "\n"

    prompt = f"""
You are Mosaic, a premium JAKAFI HCP Assistant. You help users analyze the JAKAFI alerts dataset using Retrieval-Augmented Generation (RAG).
{filter_context}
Here is the global dataset summary statistics (already filtered by the active sidebar filters):
{summary_stats}

Here are the top most relevant retrieved records from the JAKAFI database matching the user's query:
```csv
{retrieved_csv_str}
```

Instructions:
1. Answer the user's query using the retrieved JAKAFI records.
2. If the user asks about alerts needing follow-up/action/none, return the list of HCPs where follow_up_status is "None", formatted as a clean markdown table with ID, Name, Territory, Program Type, Received, and calculated Priority Score.
3. If they ask about priority list or who to contact first, rank them by calculated priority score and highlight Dr. John Smith (HCP001) which has a score of 100.
4. If they ask for summary/statistics/overview/KPIs, compute aggregate counts (Direct vs SPP Channel Rx, New Writers, New Patients tags, Required/Scheduled/Completed follow-ups) and output a premium markdown dashboard.
5. If they ask for prescription growth forecasts, use predicted next-week prescriptions (from 'Predicted_Next_Week_Rx') compared to 'current_week_rx' and list the top high-growth targets.
6. Return your answer in standard Markdown.
7. Also provide 3 suggested follow-up prompts for the user in a separate block at the very end of your response, formatted exactly as:
`SUGGESTIONS: ["Suggestion 1", "Suggestion 2", "Suggestion 3"]`

User Query: "{message}"
"""
    return prompt

def chat_api(request):
    """Handles chatbot API requests (POST only)."""
    if request.method != 'POST':
        return JsonResponse({'error': 'Invalid request method. Only POST is allowed.'}, status=400)
    
    try:
        data = json.loads(request.body)
        user_message = data.get('message', '').strip()
        filters = data.get('filters', {})
    except json.JSONDecodeError:
        return JsonResponse({'error': 'Invalid JSON format.'}, status=400)
    
    if not user_message:
        return JsonResponse({'error': 'Message content cannot be empty.'}, status=400)

    # Resolve pronouns and back-references to the last query result
    msg_lower = user_message.lower().strip().rstrip('.!?')
    short_words = set(msg_lower.split())
    pronoun_keywords = {'it', 'this', 'that', 'these', 'those', 'the', 'report', 'document',
                        'result', 'data', 'chart', 'analysis', 'info', 'information'}
    is_pronoun_ref = (
        msg_lower in pronoun_keywords
        or msg_lower in ('the report', 'the document', 'the result', 'the data', 'the chart',
                         'the analysis', 'the info', 'the information')
        or (len(short_words) <= 3 and short_words & pronoun_keywords and msg_lower not in ('help', 'hello', 'hi', 'hey'))
    )

    is_export = any(k in msg_lower for k in ['make a report', 'create a report', 'generate a report',
                                              'create a document', 'make a document',
                                              'download it', 'download this', 'export it', 'export this',
                                              'export as', 'save it', 'save as', 'save this', 'save as pdf', 'pdf'])

    df, _ = get_hcp_data_and_predictor()

    # Apply active sidebar filters
    df = apply_sidebar_filters(df, filters)

    # Retrieve api key from environment or fallback user-provided key
    api_key = os.environ.get("GEMINI_API_KEY") or "AQ.Ab8RN6I_i8lRHZ83xIETbNi0o_XVaX7qrzn9RXsPnYxBtLl5xA"
    model = "gemini-2.5-flash"

    # Serve Gemini response if api_key is present
    if api_key:
        try:
            from google import genai
            client = genai.Client(api_key=api_key)
            prompt = construct_gemini_prompt(user_message, df, filters)
            
            # Execute Gemini query from backend using dynamic model
            interaction = client.interactions.create(
                model=model,
                input=prompt
            )
            output_text = interaction.output_text
            
            # Parse suggestions
            suggestions = ["Show active JAKAFI alerts", "Who is the highest priority HCP?", "Summarize prescription KPIs", "Forecast next week's Rx growth"]
            if "SUGGESTIONS:" in output_text:
                parts = output_text.split("SUGGESTIONS:")
                main_response = parts[0].strip()
                sug_str = parts[1].strip()
                try:
                    suggestions = json.loads(sug_str)
                except Exception:
                    pass
                output_text = main_response
            
            # Store in session for pronoun/export references
            if not is_pronoun_ref:
                request.session['last_query'] = user_message
                request.session['last_response'] = output_text
                request.session['last_suggestions'] = suggestions

            return JsonResponse({
                'response': output_text,
                'suggestions': suggestions
            })
        except Exception:
            pass  # Fall back to local rule-based engine on any API query errors

    # If pronoun reference or export request with stored data, serve from session
    if (is_pronoun_ref or is_export) and request.session.get('last_response'):
        last_query = request.session['last_query']
        last_response = request.session['last_response']
        last_suggestions = request.session.get('last_suggestions',
            ["Show active JAKAFI alerts", "Summarize prescription KPIs", "Forecast next week's Rx growth"])
        download_url = '/api/chat/export/'
        text = (
            f"Here is the result from your previous query:\n\n"
            f"**You asked:** {last_query}\n\n"
            f"---\n\n"
            f"{last_response}\n\n"
            f"---\n\n"
            f"**[⬇ Download Report]({download_url})** — Click to download as a Markdown file."
        )
        return JsonResponse({'response': text, 'suggestions': last_suggestions, 'download_url': download_url})

    # Process message and determine response locally using the scoped data
    response_text, suggestions = get_chatbot_response(user_message, df, request.session)

    # Store last query result in session for pronoun/export resolution
    if not is_pronoun_ref:
        request.session['last_query'] = user_message
        request.session['last_response'] = response_text
        request.session['last_suggestions'] = suggestions
    
    # Simulate a subtle thinking delay
    time.sleep(random.uniform(0.3, 0.5))
    
    return JsonResponse({
        'response': response_text,
        'suggestions': suggestions
    })

def retrieve_relevant_rows(query, df, top_k=10):
    """Retrieves the top_k most relevant rows from the dataframe using TF-IDF similarity to the query."""
    if df.empty:
        return []
    
    # Create textual representation for each row
    row_texts = []
    for _, row in df.iterrows():
        text_parts = []
        for col in df.columns:
            text_parts.append(f"{col}: {row[col]}")
        row_texts.append(" | ".join(text_parts))
        
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    
    vectorizer = TfidfVectorizer(stop_words='english')
    # Fit and transform
    tfidf_matrix = vectorizer.fit_transform(row_texts + [query])
    similarities = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1]).flatten()
    
    # Sort indices descending
    top_indices = similarities.argsort()[::-1][:top_k]
    
    results = []
    for idx in top_indices:
        results.append(df.iloc[idx])
    return results

def parse_local_query_filters(query, df):
    """
    Parses natural language queries to dynamically filter and rank JAKAFI database columns.
    Returns: filtered_df, filters_applied, sort_by, ascending, limit
    """
    filtered_df = df.copy()
    filters_applied = []
    sort_by = None
    ascending = False
    limit = None
    
    msg = query.lower()
    
    # 1. Territory filtering
    unique_territories = df['territory'].dropna().unique()
    for t in unique_territories:
        if str(t).lower() in msg:
            filtered_df = filtered_df[filtered_df['territory'] == t]
            filters_applied.append(f"Territory: **{t}**")
            break
            
    # 2. Specialty filtering
    if 'specialty' in df.columns:
        unique_specs = df['specialty'].dropna().unique()
        for s in unique_specs:
            if str(s).lower() in msg:
                filtered_df = filtered_df[filtered_df['specialty'] == s]
                filters_applied.append(f"Specialty: **{s}**")
                break
                
    # 3. Channel filtering
    for c in ['direct', 'spp']:
        if c in msg:
            c_val = 'Direct' if c == 'direct' else 'SPP'
            filtered_df = filtered_df[filtered_df['channel'] == c_val]
            filters_applied.append(f"Channel: **{c_val}**")
            break
            
    # 4. Patient Type filtering
    if 'new patient' in msg:
        filtered_df = filtered_df[filtered_df['patient_type'] == 'New Patient']
        filters_applied.append("Patient Type: **New Patient**")
    elif 'established patient' in msg or ('established' in msg and 'writer' not in msg):
        filtered_df = filtered_df[filtered_df['patient_type'] == 'Established Patient']
        filters_applied.append("Patient Type: **Established Patient**")
        
    # 5. Writer Status filtering
    if 'new writer' in msg or 'new writers' in msg:
        filtered_df = filtered_df[filtered_df['writer_status'] == 'New Writer']
        filters_applied.append("Writer Status: **New Writer**")
    elif 'established writer' in msg or 'established writers' in msg:
        filtered_df = filtered_df[filtered_df['writer_status'] == 'Established Writer']
        filters_applied.append("Writer Status: **Established Writer**")
    elif 'lapsed writer' in msg or 'lapsed writers' in msg or 'lapsed' in msg:
        filtered_df = filtered_df[filtered_df['writer_status'] == 'Lapsed Writer']
        filters_applied.append("Writer Status: **Lapsed Writer**")
        
    # 6. Follow-up Status filtering
    if any(k in msg for k in ['action', 'pending', 'required', 'overdue', 'follow-up none']) or ('active' in msg and 'alert' in msg):
        filtered_df = filtered_df[filtered_df['follow_up_status'] == 'None']
        filters_applied.append("Follow-up: **None**")
    elif 'scheduled' in msg:
        filtered_df = filtered_df[filtered_df['follow_up_status'] == 'Scheduled']
        filters_applied.append("Follow-up: **Scheduled**")
    elif 'completed' in msg:
        filtered_df = filtered_df[filtered_df['follow_up_status'] == 'Completed']
        filters_applied.append("Follow-up: **Completed**")
        
    # 7. Sorting configuration
    if any(k in msg for k in ['priority', 'highest', 'top', 'score', 'urgent', 'urgency']):
        sort_by = 'Priority_Score'
        ascending = False
    elif any(k in msg for k in ['growth', 'forecast', 'predict', 'ml', 'trend', 'next week']):
        if 'Predicted_Next_Week_Rx' in df.columns:
            filtered_df['expected_growth'] = filtered_df['Predicted_Next_Week_Rx'] - filtered_df['current_week_rx']
            sort_by = 'expected_growth'
            ascending = False
            
    # 8. Row limit checking
    import re
    limit_match = re.search(r'\b(top|first|show|limit)\s+(\d+)\b', msg)
    if limit_match:
        limit = int(limit_match.group(2))
    elif 'top' in msg or 'highest' in msg:
        limit = 5
        
    return filtered_df, filters_applied, sort_by, ascending, limit

def generate_dynamic_filtered_report(query, df):
    """Dynamically parses queries to analyze datasets when RAG/LLM rate limit fallbacks trigger."""
    filtered_df, filters, sort_by, ascending, limit = parse_local_query_filters(query, df)
    
    if sort_by:
        filtered_df = filtered_df.sort_values(by=sort_by, ascending=ascending)
        
    total_found = len(filtered_df)
    if limit:
        filtered_df = filtered_df.head(limit)
        
    if filtered_df.empty:
        filter_str = " and ".join(filters) if filters else "those keywords"
        return f"I analyzed the JAKAFI alerts database, but found no records matching: **{filter_str}**.", ["Show active JAKAFI alerts", "Summarize prescription KPIs"]
        
    # Build dynamically formatted Markdown Table
    columns_to_show = ['hcp_id', 'hcp_name', 'specialty', 'territory', 'channel', 'patient_type', 'writer_status', 'current_week_rx', 'follow_up_status', 'Priority_Score']
    cols = [c for c in columns_to_show if c in filtered_df.columns]
    
    table_markdown = "| " + " | ".join([c.replace('_', ' ').title() for c in cols]) + " |\n"
    table_markdown += "| " + " | ".join([":---" for _ in cols]) + " |\n"
    
    for _, row in filtered_df.iterrows():
        row_vals = []
        for c in cols:
            val = row[c]
            if c == 'Priority_Score':
                row_vals.append(f"**{val}**")
            else:
                row_vals.append(str(val))
        table_markdown += "| " + " | ".join(row_vals) + " |\n"
        
    filter_desc = f" filtered by {', '.join(filters)}" if filters else ""
    sort_desc = f", sorted by **{sort_by.replace('_', ' ').title()}**" if sort_by else ""
    limit_desc = f" (showing top {limit} of {total_found} matches)" if limit and total_found > limit else f" (showing all {total_found} matching records)"
    
    text = (
        f"### 🔍 Dynamic Database Analysis\n"
        f"I analyzed the database and found JAKAFI accounts{filter_desc}{sort_desc}{limit_desc}:\n\n"
        f"{table_markdown}\n"
        f"Would you like to search for a specific doctor or summarize prescription KPIs?"
    )
    suggestions = ["Show active JAKAFI alerts", "Summarize prescription KPIs", "Forecast next week's Rx growth"]
    return text, suggestions

def get_chatbot_response(message, df, session=None):
    """Generates a data-driven response and suggestions based on JAKAFI columns using the local rule-based engine."""
    msg = message.lower().strip()
    _, predictor = get_hcp_data_and_predictor()
    
    if df.empty:
        return "I'm sorry, but the HCP database (`hcp_data.csv`) is empty. Please verify the dataset status.", ["Show JAKAFI Summary"]

    # 0. QUERY: Export / Report / Download request (not a database query)
    is_export = any(k in msg for k in ['make a report', 'create a report', 'generate a report', 'create a document', 'make a document',
                                        'download it', 'download this', 'export it', 'export this', 'export as',
                                        'save it', 'save as', 'save this', 'save as pdf', 'pdf'])
    if is_export:
        last_query = session.get('last_query', '') if session else ''
        last_response = session.get('last_response', '') if session else ''
        if last_response:
            return (
                f"Here is the result from your previous query:\n\n"
                f"**You asked:** {last_query}\n\n"
                f"---\n\n"
                f"{last_response}\n\n"
                f"---\n\n"
                f"To save this:\n"
                f"• **Copy** the content above and paste it into a document editor.\n"
                f"• **Print to PDF**: Right-click → **Print** → **Save as PDF**.\n"
                f"• **Screenshot**: Capture the section with your screen capture tool."
            ), session.get('last_suggestions', ["Show active JAKAFI alerts", "Summarize prescription KPIs", "Forecast next week's Rx growth"])
        else:
            return (
                "There is no previous result to export yet. Please ask a question first "
                "(e.g., 'Show active alerts', 'Summarize KPIs', or 'Forecast next week'), "
                "then use **download/export/save** to store the result.\n\n"
                "To save responses once available:\n"
                "• **Copy** the response and paste it into a document editor.\n"
                "• **Print to PDF**: Right-click → **Print** → **Save as PDF**.\n"
                "• **Screenshot**: Capture the section with your screen capture tool."
            ), ["Show active JAKAFI alerts", "Summarize prescription KPIs", "Forecast next week's Rx growth"]

    # 1. QUERY: Follow-up needed / Active alerts (follow_up_status == 'None')
    if any(k in msg for k in ['alert', 'follow-up', 'follow up', 'followup', 'action', 'pending', 'overdue']):
        action_df = df[df['follow_up_status'] == 'None'].copy()
        
        if action_df.empty:
            return "Good news! All JAKAFI alerts have active follow-ups scheduled or completed. No immediate actions are needed.", ["Show highest priority HCP", "Summarize prescription KPIs"]
            
        # Sort by Priority Score descending
        action_sorted = action_df.sort_values(by='Priority_Score', ascending=False)
        count = len(action_sorted)
        
        # Build Table
        table_markdown = "| HCP ID | HCP Name | Territory | Program Type | Received | Priority Score |\n"
        table_markdown += "| :--- | :--- | :--- | :--- | :--- | :--- |\n"
        
        for _, row in action_sorted.head(15).iterrows():
            table_markdown += f"| {row['hcp_id']} | {row['hcp_name']} | {row['territory']} | {row['program_type']} | {row['received_date']} | **{row['Priority_Score']}** |\n"
            
        top_hcp_name = action_sorted.iloc[0]['hcp_name'] if not action_sorted.empty else "N/A"
        top_hcp_id = action_sorted.iloc[0]['hcp_id'] if not action_sorted.empty else ""
        
        text = (
            f"There are **{count} JAKAFI alerts** requiring follow-up (Follow-up status: **None**).\n\n"
            f"Here are the active alerts (showing top 15), ranked by target engagement score:\n\n"
            f"{table_markdown}\n"
            f"**{top_hcp_name}** ({top_hcp_id}) is currently the highest priority lead requiring follow-up. Ask about **{top_hcp_name}** to view their profile."
        )
        suggestions = ["Who is the highest priority HCP?", f"Search {top_hcp_name}", "Summarize prescription KPIs", "Forecast next week's Rx growth"]
        return text, suggestions

    # 2. QUERY: Top Priority HCPs
    elif any(k in msg for k in ['priority', 'priority list', 'highest priority', 'who to contact first', 'highest score']):
        priority_sorted = df.sort_values(by='Priority_Score', ascending=False).head(5)
        
        # Highlight Top HCP
        top_hcp = df.sort_values(by='Priority_Score', ascending=False).iloc[0] if not df.empty else None
        top_detail = ""
        if top_hcp is not None:
            top_detail = (
                f"### ⭐ Top Priority Lead: {top_hcp['hcp_name']}\n"
                f"• **HCP ID**: {top_hcp['hcp_id']} (Territory: {top_hcp['territory']}, Specialty: {top_hcp.get('specialty', 'N/A')})\n"
                f"• **Priority Engagement Score**: {top_hcp['Priority_Score']}/100\n"
                f"• **Key Reasons**: \n"
                f"  - Program Type: **{top_hcp['program_type']}** ({top_hcp.get('event_type', 'N/A')} event received on {top_hcp.get('received_date', 'N/A')}).\n"
                f"  - Follow-up status: **{top_hcp['follow_up_status']}**.\n"
                f"  - Active writing profile: **{top_hcp['writer_status']}** with a **{top_hcp['patient_type']}** tag.\n"
                f"  - weekly prescribing volume: CW **{top_hcp['current_week_rx']} Rx** (PW: {top_hcp['prior_week_rx']} Rx).\n\n"
            )

        # Build Table
        table_markdown = "| Rank | HCP ID | Name | Territory | Channel | Score | Primary Reason |\n"
        table_markdown += "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n"
        
        for idx, (_, row) in enumerate(priority_sorted.iterrows(), 1):
            main_reason = row['Priority_Reasons'].split('; ')[0] if ';' in row['Priority_Reasons'] else row['Priority_Reasons']
            table_markdown += f"| #{idx} | {row['hcp_id']} | {row['hcp_name']} | {row['territory']} | {row['channel']} | **{row['Priority_Score']}** | {main_reason} |\n"
            
        text = (
            f"{top_detail}"
            f"### 📋 Top 5 Urgency Leads:\n"
            f"Here are the top-ranked HCP alerts based on target engagement urgency:\n\n"
            f"{table_markdown}\n"
            f"Would you like to search for a specific doctor or summarize prescription KPIs?"
        )
        suggestions = ["Show active JAKAFI alerts", "Summarize prescription KPIs", "Forecast next week's Rx growth"]
        return text, suggestions

    # 3. QUERY: Summarize prescription KPIs
    elif any(k in msg for k in ['summary', 'stats', 'statistics', 'overview', 'dashboard', 'kpi', 'rx']):
        total_hcps = len(df)
        total_crx = df['current_week_rx'].sum()
        total_prx = df['prior_week_rx'].sum()
        growth = ((total_crx - total_prx) / total_prx * 100) if total_prx > 0 else 0
        
        # Channel KPIs
        direct_rx = df[df['channel'] == 'Direct']['current_week_rx'].sum()
        spp_rx = df[df['channel'] == 'SPP']['current_week_rx'].sum()
        
        # Patient Type KPIs
        new_patients = len(df[df['patient_type'] == 'New Patient'])
        est_patients = len(df[df['patient_type'] == 'Established Patient'])
        
        # Writer Status KPIs
        new_writers = len(df[df['writer_status'] == 'New Writer'])
        est_writers = len(df[df['writer_status'] == 'Established Writer'])
        lapsed_writers = len(df[df['writer_status'] == 'Lapsed Writer'])
        
        # Follow-up status KPIs
        none_cnt = len(df[df['follow_up_status'] == 'None'])
        sched_cnt = len(df[df['follow_up_status'] == 'Scheduled'])
        comp_cnt = len(df[df['follow_up_status'] == 'Completed'])
        
        # Early Adopters vs Opt-outs
        early_adopters = len(df[df['xr_early_adopter'].isin(['Yes', 'Y'])])
        opt_outs = len(df[df['rte_opt_out'].isin(['Yes', 'Y'])])
        
        text = (
            f"### 📊 JAKAFI Alert & Prescription KPIs Dashboard\n"
            f"Here is the overall analytics overview for JAKAFI accounts:\n\n"
            f"#### 📈 Prescription Volume (Weekly comparison):\n"
            f"• **Current Week Rx (CW)**: {total_crx} prescriptions\n"
            f"• **Prior Week Rx (PW)**: {total_prx} prescriptions (Growth: **{growth:+.1f}%**)\n"
            f"• **Direct Channel Rx**: {direct_rx} prescriptions\n"
            f"• **SPP Channel Rx**: {spp_rx} prescriptions\n\n"
            f"#### 👥 HCP writer profiles:\n"
            f"• **New Writers**: {new_writers} writers\n"
            f"• **Established Writers**: {est_writers} writers\n"
            f"• **Lapsed Writers**: {lapsed_writers} writers\n"
            f"• **New Patient alert tags**: {new_patients} accounts\n"
            f"• **XR Early Adopters**: {early_adopters} accounts\n"
            f"• **RTE Opt-outs**: {opt_outs} accounts\n\n"
            f"#### 📅 Follow-up alerts status:\n"
            f"• **Required (None)**: {none_cnt} accounts 🔴\n"
            f"• **Scheduled**: {sched_cnt} accounts 🟡\n"
            f"• **Completed**: {comp_cnt} accounts 🟢\n"
        )
        suggestions = ["Show active JAKAFI alerts", "Who is the highest priority HCP?", "Forecast next week's Rx growth"]
        return text, suggestions

    # 4. QUERY: ML Predictions / Trend Forecasting
    elif any(k in msg for k in ['predict', 'prediction', 'forecast', 'trend', 'ml', 'growth', 'next week']):
        # Expected growth
        df['expected_growth'] = df['Predicted_Next_Week_Rx'] - df['current_week_rx']
        growth_sorted = df.sort_values(by='expected_growth', ascending=False).head(5)
        
        table_markdown = "| HCP ID | Name | Territory | Channel | Current Rx | Predicted Next Rx | Expected Growth | Score |\n"
        table_markdown += "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n"
        
        for _, row in growth_sorted.iterrows():
            growth_sign = "+" if row['expected_growth'] >= 0 else ""
            table_markdown += (
                f"| {row['hcp_id']} | {row['hcp_name']} | {row['territory']} | {row['channel']} | "
                f"{row['current_week_rx']} | {row['Predicted_Next_Week_Rx']} | {growth_sign}{row['expected_growth']:.1f} | **{row['Priority_Score']}** |\n"
            )
            
        text = (
            f"### 🤖 Random Forest Trend Forecast (JAKAFI Prescription Volumes)\n"
            f"Expected prescribing volume for next week, calculated using: writer statuses, "
            f"opt-out preferences, and alert recency.\n\n"
            f"Here are the **Top 5 predicted growth HCPs** for next week:\n\n"
            f"{table_markdown}\n"
            f"**Action item:** Target these high-growth accounts if they have a pending follow-up (None)."
        )
        suggestions = ["Show active JAKAFI alerts", "Who is the highest priority HCP?", "Summarize prescription KPIs"]
        return text, suggestions

    # 5. QUERY: Search by Doctor Name, HCP ID, or Specialty
    elif any(h in msg for h in ['hcp', 'dr.', 'dr ', 'doctor', 'specialty', 'speciality', 'profile', 'search', 'find', 'details']):
        # Extract query words
        query_words = [w.strip(',').lower() for w in msg.split() if len(w.strip(',')) > 2 and w.lower() not in ['hcp', 'dr.', 'dr', 'doctor', 'show', 'profile', 'search', 'find', 'details', 'for', 'about', 'specialty', 'speciality']]
        matches = []
        for _, row in df.iterrows():
            row_id = str(row['hcp_id']).lower()
            row_name = str(row['hcp_name']).lower()
            row_specialty = str(row.get('specialty', '')).lower()
            if row_id in msg or any(w in row_name for w in query_words) or any(w in row_specialty for w in query_words):
                matches.append(row)
                
        if not matches:
            return "I couldn't find an HCP matching that name, ID, or specialty in the database. Please try searching using a name or ID.", ["Show active JAKAFI alerts", "Summarize prescription KPIs"]
            
        if len(matches) == 1:
            row = matches[0]
            prior_rx = row['prior_week_rx']
            current_rx = row['current_week_rx']
            growth = ((current_rx - prior_rx) / prior_rx * 100) if prior_rx > 0 else 0
            growth_str = f"+{growth:.1f}%" if growth >= 0 else f"{growth:.1f}%"
            
            text = (
                f"### 👤 JAKAFI Alert Details: {row['hcp_name']}\n"
                f"• **HCP ID**: {row['hcp_id']} (Specialty: {row.get('specialty', 'N/A')})\n"
                f"• **Territory**: {row['territory']} (Channel: {row['channel']})\n"
                f"• **Brand**: {row['brand']}\n\n"
                f"#### 📊 Alert Metrics:\n"
                f"• **Writer Status**: {row['writer_status']}\n"
                f"• **Patient Type**: {row['patient_type']}\n"
                f"• **Current Week Rx**: {current_rx} prescriptions\n"
                f"• **Prior Week Rx**: {prior_rx} prescriptions (Growth: {growth_str})\n"
                f"• **Predicted Next Week Rx**: {row['Predicted_Next_Week_Rx']} prescriptions\n\n"
                f"#### 📅 Program Event:\n"
                f"• **Program Type**: {row['program_type']} ({row.get('event_type', 'N/A')})\n"
                f"• **Program Date**: {row['program_date']}\n"
                f"• **Received Date**: {row['received_date']}\n\n"
                f"#### 🤝 Follow-up Status:\n"
                f"• **Follow-up Status**: **{row['follow_up_status']}**\n"
                f"• **RTE Opt Out**: {row['rte_opt_out']}\n"
                f"• **XR Early Adopter**: {row['xr_early_adopter']}\n"
                f"• **Priority Score**: **{row['Priority_Score']}/100**\n"
                f"• **System Notes**: {row['Priority_Reasons']}"
            )
            suggestions = ["Show active JAKAFI alerts", "Who is the highest priority HCP?", "Summarize prescription KPIs"]
            return text, suggestions
        else:
            list_str = ""
            for r in matches[:15]:
                list_str += f"• **{r['hcp_name']}** ({r['hcp_id']} in {r['territory']}) - Score: {r['Priority_Score']}\n"
            text = (
                f"I found **{len(matches)} matching JAKAFI accounts**:\n\n"
                f"{list_str}\n"
                f"Please search for the full name or ID to see detailed parameters."
            )
            suggestions = [f"Search {m['hcp_name']}" for m in matches[:3]]
            return text, suggestions

    # 6. QUERY: Territory filtering
    else:
        # Check if query contains any territory name from the database
        target_t = None
        unique_territories = df['territory'].dropna().unique()
        for t in unique_territories:
            if str(t).lower() in msg:
                target_t = t
                break
                
        if target_t is not None:
            t_df = df[df['territory'] == target_t]
            total_rx = t_df['current_week_rx'].sum()
            overdue_cnt = len(t_df[t_df['follow_up_status'] == 'None'])
            early_adopters = len(t_df[t_df['xr_early_adopter'].isin(['Yes', 'Y'])])
            
            t_sorted = t_df.sort_values(by='Priority_Score', ascending=False).head(3)
            
            table_markdown = "| HCP ID | Name | Channel | Current Rx | Followup | Score |\n"
            table_markdown += "| :--- | :--- | :--- | :--- | :--- | :--- |\n"
            for _, row in t_sorted.iterrows():
                table_markdown += f"| {row['hcp_id']} | {row['hcp_name']} | {row['channel']} | {row['current_week_rx']} | {row['follow_up_status']} | **{row['Priority_Score']}** |\n"
                
            text = (
                f"### 📍 Territory Report: {target_t}\n"
                f"Analytics for active JAKAFI accounts in **{target_t}**:\n\n"
                f"• **Active Alerts**: {len(t_df)} accounts\n"
                f"• **Current Week Rx**: {total_rx} prescriptions\n"
                f"• **Follow-ups required (None)**: {overdue_cnt} alerts 🔴\n"
                f"• **XR Early Adopters**: {early_adopters} accounts\n\n"
                f"#### Top Priority HCPs in {target_t}:\n"
                f"{table_markdown}"
            )
            suggestions = ["Show active JAKAFI alerts", "Summarize prescription KPIs", "Who is the highest priority HCP?"]
            return text, suggestions

        # 7. Greeting & Default Help
        elif any(greeting in msg for greeting in ['hello', 'hi', 'hey', 'greetings', 'hola', 'yo']):
            text = (
                "Hello! I am your **Mosaic JAKAFI Analytical Assistant**.\n\n"
                "I have loaded the JAKAFI alerts dataset (`data/hcp_data.csv`) and trained the Random Forest prescription predictor.\n\n"
                "How can I assist you today? I can help you search details regarding any parameter:\n"
                "• **Alerts**: Ask 'show active alerts' to see entries with no follow-up (`follow_up_status` == 'None').\n"
                "• **Priorities**: Ask 'who is the highest priority HCP?' or 'show priority list'.\n"
                "• **KPI Dashboard**: Ask 'summarize prescription KPIs' to see channel, writer status, and patient type metrics.\n"
                "• **Forecast**: Ask 'forecast next week' to view predicted prescription growth."
            )
            suggestions = ["Show active JAKAFI alerts", "Who is the highest priority HCP?", "Summarize prescription KPIs", "Forecast next week's Rx growth"]
            return text, suggestions

        # Fallback default
        else:
            # Check if any dynamic filters can be parsed from natural language input
            parsed_df, filters, _, _, _ = parse_local_query_filters(message, df)
            if filters or any(w in msg for w in ['hematology', 'oncology', 'medicine', 'direct', 'spp', 'patient', 'writer', 'priority', 'growth', 'forecast', 'territory', 'specialty']):
                return generate_dynamic_filtered_report(message, df)
                
            text = (
                "I am programmed to analyze the JAKAFI alerts database. I can only assist with query requests related to the columns:\n"
                "• `hcp_id`, `hcp_name`, `specialty`\n"
                "• `territory` (Territory-01, Territory-02, Chennai, Delhi, etc.)\n"
                "• `brand` (JAKAFI)\n"
                "• `channel` (Direct/SPP)\n"
                "• `patient_type` (New/Established Patient)\n"
                "• `writer_status` (New/Established/Lapsed Writer)\n"
                "• `prior_week_rx`, `current_week_rx`\n"
                "• `program_type`, `event_type`\n"
                "• `program_date`, `received_date`\n"
                "• `follow_up_status` (None/Scheduled/Completed)\n"
                "• `rte_opt_out`, `xr_early_adopter`\n\n"
                "Please ask a question related to these parameters."
            )
            suggestions = ["Show active JAKAFI alerts", "Who is the highest priority HCP?", "Summarize prescription KPIs", "Forecast next week's Rx growth"]
            return text, suggestions
